steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/$REPO_NAME:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/$REPO_NAME:$COMMIT_SHA'
      - .
    id: Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/github.com/$REPO_NAME'
    id: Push
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - SHORT_SHA=$SHORT_SHA
    args:
      - infra-manager
      - deployments
      - apply
      - 'projects/$PROJECT_ID/locations/us-central1/deployments/tree-drawing'
      - '--service-account=projects/$PROJECT_ID/serviceAccounts/terraform-runner@millennia-tech-tree-grapher.iam.gserviceaccount.com'
      - '--git-source-repo=https://github.com/Ranamar/millennia.git'
      - '--git-source-directory=deploy'
      - '--git-source-ref=main'
images:
  - 'gcr.io/$PROJECT_ID/github.com/$REPO_NAME:latest'
  - 'gcr.io/$PROJECT_ID/github.com/$REPO_NAME:$COMMIT_SHA'
