steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - >-
        gcr.io/$PROJECT_ID/github.com/$REPO_NAME:latest
      - .
    id: Build
  - name: gcr.io/cloud-builders/gcloud
    env:
      - SHORT_SHA=$SHORT_SHA
    args:
      - infra-manager
      - deployments
      - apply
      - >-
        projects/$PROJECT_ID/locations/us-central1/deployments/tree-drawing
      - >-
        --service-account=projects/$PROJECT_ID/serviceAccounts/terraform-runner@millennia-tech-tree-grapher.iam.gserviceaccount.com
      - '--git-source-repo=https://github.com/Ranamar/millennia.git'
      - '--git-source-directory=deploy'
      - '--git-source-ref=main'
    id: Apply
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - tech-tree-grapher
      - '--platform=managed'
      - >-
        --image=gcr.io/$PROJECT_ID/github.com/$REPO_NAME:latest
      - >-
        --labels=commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - '--region=us-central1'
    id: Deploy
    entrypoint: gcloud
timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - >-
    gcr.io/$PROJECT_ID/github.com/$REPO_NAME:latest
